// src/lib/argentina.js
export const provincias = [
  'Buenos Aires',
  'CABA',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucumán',
]

export const ciudadesPorProvincia = {
  'Buenos Aires': ['La Plata', 'Mar del Plata', 'Quilmes', 'Lanús', 'General Pueyrredón', 'Lomas de Zamora', 'Almirante Brown', 'Florencio Varela', 'San Martín', 'Morón', 'Tigre', 'Merlo', 'Bahía Blanca', 'Tandil', 'Junín', 'Pergamino', 'San Nicolás'],
  'CABA': ['Palermo', 'Belgrano', 'Recoleta', 'San Telmo', 'Flores', 'Caballito', 'Villa Crespo', 'Almagro', 'Barracas', 'La Boca', 'Núñez', 'Saavedra', 'Colegiales', 'Villa Urquiza'],
  'Catamarca': ['San Fernando del Valle de Catamarca', 'Andalgalá', 'Belén', 'Santa María', 'Tinogasta'],
  'Chaco': ['Resistencia', 'Presidencia Roque Sáenz Peña', 'Villa Ángela', 'Charata', 'General San Martín'],
  'Chubut': ['Rawson', 'Comodoro Rivadavia', 'Trelew', 'Puerto Madryn', 'Esquel'],
  'Córdoba': ['Córdoba', 'Villa Carlos Paz', 'Río Cuarto', 'San Francisco', 'Villa María', 'Río Tercero', 'Alta Gracia', 'La Falda'],
  'Corrientes': ['Corrientes', 'Goya', 'Mercedes', 'Bella Vista', 'Paso de los Libres'],
  'Entre Ríos': ['Paraná', 'Concordia', 'Gualeguaychú', 'Concepción del Uruguay', 'Colón'],
  'Formosa': ['Formosa', 'Clorinda', 'Pirané', 'El Colorado'],
  'Jujuy': ['San Salvador de Jujuy', 'Palpalá', 'Libertador General San Martín', 'Tilcara', 'Humahuaca'],
  'La Pampa': ['Santa Rosa', 'General Pico', 'Toay', 'Realicó'],
  'La Rioja': ['La Rioja', 'Chilecito', 'Aimogasta', 'Chamical'],
  'Mendoza': ['Mendoza', 'San Rafael', 'Godoy Cruz', 'Las Heras', 'Guaymallén', 'Maipú', 'Luján de Cuyo', 'Rivadavia'],
  'Misiones': ['Posadas', 'Oberá', 'Eldorado', 'Puerto Iguazú', 'Apóstoles'],
  'Neuquén': ['Neuquén', 'San Martín de los Andes', 'Villa La Angostura', 'Zapala', 'Cutral Có'],
  'Río Negro': ['Viedma', 'San Carlos de Bariloche', 'General Roca', 'Cipolletti', 'El Bolsón'],
  'Salta': ['Salta', 'San Ramón de la Nueva Orán', 'Tartagal', 'Güemes', 'Cafayate'],
  'San Juan': ['San Juan', 'Rawson', 'Rivadavia', 'Santa Lucía', 'Pocito'],
  'San Luis': ['San Luis', 'Villa Mercedes', 'Merlo', 'Juana Koslay'],
  'Santa Cruz': ['Río Gallegos', 'Caleta Olivia', 'El Calafate', 'Puerto Madryn', 'Pico Truncado'],
  'Santa Fe': ['Santa Fe', 'Rosario', 'Rafaela', 'Venado Tuerto', 'Reconquista', 'Santo Tomé', 'Villa Constitución'],
  'Santiago del Estero': ['Santiago del Estero', 'La Banda', 'Termas de Río Hondo', 'Añatuya'],
  'Tierra del Fuego': ['Ushuaia', 'Río Grande', 'Tolhuin'],
  'Tucumán': ['San Miguel de Tucumán', 'Yerba Buena', 'Tafí Viejo', 'Concepción', 'Aguilares', 'Banda del Río Salí'],
}
